@startuml
actor User

User -> TelegramBotLayer : link
return response

TelegramBotLayer -> ServiceLayer : link
return response

ServiceLayer -> HostingApi : link
alt youtube
    HostingApi -> YouTubeHostingApi: YouTube link
    return view count
else vk
    HostingApi -> VkHostingApi: VK link
    return view count
end

ServiceLayer -> LinkRepository : LinkDto
return boolean

LinkRepository -> QueryExecutor : sql
return boolean

database PostgreSQL

QueryExecutor -> PostgreSQL : execute query
return ResultSet
@enduml